### ISSUE TITLE
oekofen-pellematic-compact

### ISSUE THREAD

**Issue by lucaferrucci** [dominikamann/oekofen-pellematic-compact#1]
Errore
Impossibile caricare il flusso di configurazione: {"message":"Invalid handler specified"}

**Comment by dominikamann** [comment]
Hi, thank you for using my integration it is currently in development. I will inform you as soon as it is ready. You can follow the following instruction to get your Pellematic Compact connected: https://github.com/dominikamann/HomeAssistant-Oekofen-Pellematic-REST-Template

**Comment by lucaferrucci** [comment]
hello, although I followed your guide carefully, I can't get the integration to work, I'm missing something, I'll try again

**Comment by dominikamann** [comment]
@lucaferrucci the integration is now available and can be installed over HACS. Alternative you can copy the whole "oekofen-pellematic-compact" into your "custom_components" folder.

**Comment by lucaferrucci** [comment]
![Schermata 2023-01-10 alle 12 46 43](https://user-images.githubusercontent.com/110548623/211543732-c224c9e7-9044-47ef-b76e-1ca0b53b7891.jpg)
 This is my error
grrrr.........

**Comment by dominikamann** [comment]
@lucaferrucci how did you installed the plug-in?

**Comment by lucaferrucci** [comment]
Hello and thanks for the prompt response, I solved it, I don't know why a file was missing in the download of the "custom component" folder, now everything is ok.
the thing that I didn't understand, but I think it depends on okofen, the solar system and the second heating circuit are missing in the entities.
I wanted to thank you because you really did an excellent job

**Comment by dominikamann** [comment]
Great! Iam happy that it is working now 👍

**Comment by dominikamann** [comment]
@lucaferrucci i would appreciate it if you could provide me with your JSON file then I could extend the integration for you.

**Comment by lucaferrucci** [comment]
perfect, if I can extract it I'll send it to you

**Comment by dominikamann** [comment]
Thanks! If you need help let me know. Please start a "Discussion"->"Idea" (https://github.com/dominikamann/oekofen-pellematic-compact/discussions/categories/ideas) for you integration wish 👍
