### ISSUE TITLE
🚀 Release 2.0.0 is available

### ISSUE THREAD

**Issue by lucaferrucci** [dominikamann/oekofen-pellematic-compact#10]
hello dominque, nice job, but a puffer probe is always missing, in reality there are 4, hot water, tpo, tpm and tank below, which would be the one that starts the solar pump

### Discussed in https://github.com/dominikamann/oekofen-pellematic-compact/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **dominikamann** February  8, 2023</sup>
### **Features:**

- Enables configuration of the number of heating circuits 
- Enables configuration of solar/sun support

![grafik](https://user-images.githubusercontent.com/29973737/217624206-831311b6-7284-49c9-bc29-8928bd65de6f.png)

### **Warnig:**

New configuration options have been added which may cause a break. Please check if your system still works after the update. If not, please delete your device and configure it again.

<hr /><em>This discussion was created from the release <a href='https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v2.0.0'>🚀 Enables configuration of the number of heating circuits and solar/sun support</a>.</em></div>

**Comment by dominikamann** [comment]
Great ... I will add it. Do you think the names are correct:

L_koll_temp: "Solar Thermal Collector Circuit Temperature"
L_spu: "Solar Thermal Circuit Temperature"
spu_max: "Solar Thermal Circuit Temperature Max"

Please confirm then i will publish a release.

Thanks
________________________________
Von: lucaferrucci ***@***.***>
Gesendet: Donnerstag, 9. Februar 2023 13:24
An: dominikamann/oekofen-pellematic-compact ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [dominikamann/oekofen-pellematic-compact] 🚀 Release 2.0.0 is available (Issue #10)


hello dominque, nice job, but a puffer probe is always missing, in reality there are 4, hot water, tpo, tpm and tank below, which would be the one that starts the solar pump

Discussed in #9<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdominikamann%2Foekofen-pellematic-compact%2Fdiscussions%2F9&data=05%7C01%7C%7C9de2a8465cd948ce37c608db0a988b0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115422497387855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zrizspMIkZum3%2FA%2BJds8XbYd7OZ8kieXdd5HBcbKxKU%3D&reserved=0>

Originally posted by dominikamann February 8, 2023

Features:

  *   Enables configuration of the number of heating circuits
  *   Enables configuration of solar/sun support

[grafik]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29973737%2F217624206-831311b6-7284-49c9-bc29-8928bd65de6f.png&data=05%7C01%7C%7C9de2a8465cd948ce37c608db0a988b0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115422497387855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QOj9Za5HJtTSD3T0Lre0BSAa0hjAPjkt%2FAmKCQ3PC8k%3D&reserved=0>

Warnig:

New configuration options have been added which may cause a break. Please check if your system still works after the update. If not, please delete your device and configure it again.

________________________________
This discussion was created from the release 🚀 Enables configuration of the number of heating circuits and solar/sun support<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdominikamann%2Foekofen-pellematic-compact%2Freleases%2Ftag%2Fv2.0.0&data=05%7C01%7C%7C9de2a8465cd948ce37c608db0a988b0c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115422497387855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g5Z%2B2%2FiRvf8TuF7xRAwrlYfRAjErW%2Ffhyaefpf0SY1k%3D&reserved=0>.

**Comment by lucaferrucci** [comment]
correct name in red, thanks thanks thanks

ps: i am also updating my dashboard thanks to you for the amazing work

**Comment by dominikamann** [comment]
Hi,

it's released. See https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v2.0.1
Version: v2.0.1
[https://opengraph.githubassets.com/38d9779f52432064460ae6d2b419fb4d0bfc3e5c37a48de4eadca88d0d4d6887/dominikamann/oekofen-pellematic-compact/releases/tag/v2.0.1]<https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v2.0.1>
Release Implement lower buffer temperature (solar) and fix naming of TPM · dominikamann/oekofen-pellematic-compact<https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v2.0.1>
Features: Implement "Solar Thermal Buffer Storage Temperature lower area" & "Solar Thermal Buffer Storage Temperature Max" Fixes: Change "Buffer Storage Temperature lower area" to "Buffer Storag...
github.com
Thank you for using it 🙂


________________________________
Von: lucaferrucci ***@***.***>
Gesendet: Donnerstag, 9. Februar 2023 16:57
An: dominikamann/oekofen-pellematic-compact ***@***.***>
Cc: Dominik Amann ***@***.***>; Comment ***@***.***>
Betreff: Re: [dominikamann/oekofen-pellematic-compact] 🚀 Release 2.0.0 is available (Issue #10)


correct name in red, thanks thanks thanks

ps: i am also updating my dashboard thanks to you for the amazing work

**Comment by lucaferrucci** [comment]
Fantastic, tahnk you very much
