### ISSUE TITLE
Sensor for L_ontemp_act = Hot water circuit actual temp missing

### ISSUE THREAD

**Issue by RalfPfitzner** [dominikamann/oekofen-pellematic-compact#16]
Hi Dominik, 

I'm running a Pellematic Smart XS and when I fetch the values for ww1 manually via REST I get a value for L_ontemp_act which is representing the actual hot water circuit temperature.

This value is not showing up when using your custom integration.

Can you check on this?
If required I can provide logs or REST outputs.

Thanks for doing such awesome work!!

Regards
Ralf

**Comment by dominikamann** [comment]
Hi Ralf,

thank you!

I double checked it. The L_ontemp_act is implemented. The name of the sensor is "Hot Water Circuit Temperature on".

Is this sensor showing no values in HomeAssistant?

Best regards

**Comment by RalfPfitzner** [comment]
Hi Dominik,

yes, this sensor is showing values. I was thinking of another meaning with the naming of the sensor.

Thanks for clarification!

Regards
Ralf

**Comment by RalfPfitzner** [comment]
Explanation of sensor given. Working as expected.

**Comment by dominikamann** [comment]
If you want we can rename the sensor values. Just let me know what makes more sense in your point of view 👍
