### ISSUE TITLE
Pellet numbering is broken

### ISSUE THREAD

**Issue by MrRagga-** [dominikamann/oekofen-pellematic-compact#30]
It looks like you broke the name numbering in case you have multiple peX here https://github.com/dominikamann/oekofen-pellematic-compact/commit/ac6ec872f3257304906708844238fdc6fb76ed81#diff-07cd336911bfa0d50dcf13474bf76fb9aeda3a6ea9d1b08b1448da322e94ed6dR161

```
>>> "foo".format(" " + str(2))
'foo'
```

<img width="310" alt="image" src="https://github.com/dominikamann/oekofen-pellematic-compact/assets/2078752/01dd1054-9ceb-43ab-bc68-d55921d83c1f">

It should look like Heater Modulation PE 1
It should look like Heater Modulation PE 2

You did not like the previous syntax, where it was working?

**Comment by dominikamann** [comment]
May it happened by accident. I will double check it. Thanks
