### ISSUE TITLE
pellematic Pellet 1 Usage Today - always 0

### ISSUE THREAD

**Issue by wtedeschi** [dominikamann/oekofen-pellematic-compact#37]
Dear community,

Most of the sensors work fine but pellet usage is always zero.
Not sure what is going on, any hint?

The operating device is Touch V4.00b

Thanks a lot!

**Comment by thebjoernborchers** [comment]
Hi. 
Do you have pellet consumption enabled at your machine? Depending on the Oekofen device you are using it is required to have the latest Version running. I believe it is V4.02a. And depending on the sensors of your Oekofen you would need a additional sensor.

**Comment by lucaferrucci** [comment]
I have value "0" even with version 4.02b

**Comment by dominikamann** [comment]
@wtedeschi were you able to solve the problem?

**Comment by lucaferrucci** [comment]
It would seem that the magical Domink has solved it, but being daily statistics I will have the exact data tomorrow, I will certainly update you

**Comment by lucaferrucci** [comment]
It's Ok, magic Domink

![ Screenshot 2023-11-07 alle 10 04 02](https://github.com/dominikamann/oekofen-pellematic-compact/assets/110548623/4644da5f-0489-46e3-bfc4-294f981abc44) ![ Screenshot 2023-11-07 alle 10 03 52](https://github.com/dominikamann/oekofen-pellematic-compact/assets/110548623/1d74c740-ac3a-4f2a-ac77-0611fed6deae)
