### ISSUE TITLE
The last version of HA [2024.1.6] not work with pellematic

### ISSUE THREAD

**Issue by Disciplus86** [dominikamann/oekofen-pellematic-compact#44]
The service pellematic is unaviable after upgrade of Home assistant [2024.1.6].
Do you have the same problem?

**Comment by dominikamann** [comment]
For me it works fine. 

![image](https://github.com/dominikamann/oekofen-pellematic-compact/assets/29973737/656820a4-e0f8-41d8-82dd-e37e0cc21746)

![image](https://github.com/dominikamann/oekofen-pellematic-compact/assets/29973737/270754bb-e4cb-4dc6-a233-734888b60b0d)

**Comment by Disciplus86** [comment]
I will verify my config, maybe a modify IP with DHCP...
I search to verify the url of the json, but i dont see the file to change it...

**Comment by Disciplus86** [comment]
it s ok... it s me sorry, The IP have change......

**Comment by dominikamann** [comment]
I use static IPs for all my IoT-Devices. This works good 👍 Ok thanks for the info. So I will close this issue as solved.
