### ISSUE TITLE
Problem with French accented characters

### ISSUE THREAD

**Issue by Disciplus86** [dominikamann/oekofen-pellematic-compact#49]
Hello,

I'm having problems displaying variables or when text in French is displayed :
Pellematic Heating Circuit 1 State : Mode r?duit actif|T ext sup?rieure ? la limite de r?duit
or 
Pellematic State : Mise ? l'arr?t
Do you think is possible to modify this?

Thanks for your project !
Regards

**Comment by dominikamann** [comment]
Hi,

can you post the JSON result of your Ökofen Interface here? Then I can take a look at this issue.

Dominik

**Comment by loicguiraud** [comment]
![image](https://github.com/dominikamann/oekofen-pellematic-compact/assets/77931772/97e0dfc6-ab99-44ca-8428-b93d89b00aa1)
I don't have accent problems on my side in French

**Comment by dominikamann** [comment]
Mhh strange then i will close the issue.
