### ISSUE TITLE
No data 

### ISSUE THREAD

**Issue by BobMoran88** [dominikamann/oekofen-pellematic-compact#52]
Hello,

i followed the instructions and activated the JSON Interface. Got the JSON password and the IP and entered everything in the integration. But i can´t get any data. 

I installed everything and tried it again, but it still doesn´t work. 

![32cbfb5c34a3073c6891c5ab8800918e](https://github.com/dominikamann/oekofen-pellematic-compact/assets/121692910/e1f0b32d-4e65-4518-bc91-a6b5835b6231)
![966872d6a983832a836894cb27fbad26](https://github.com/dominikamann/oekofen-pellematic-compact/assets/121692910/e1c4d350-5804-4808-bf1a-a68961258147)

**Comment by lucaferrucci** [comment]
hi, what software version do you have of okofen? consider that you should have at least 4.01

**Comment by dominikamann** [comment]
What happens if you open the URL directly in Browser?

**Comment by BobMoran88** [comment]
Hello and thanks for your help!
I don´t know what solved the problem, but now everything works fine.  I didn´t change anything, though.

**Comment by froumizen** [comment]
Bonjour, 
ayant ce problème je me permet d'intervenir sur cette conversation.
Lorsque j'ouvre l'URL dans le navigateur cela ne fonctionne pas.
Merci
