### ISSUE TITLE
No second heating circuit

### ISSUE THREAD

**Issue by snuff0815** [dominikamann/oekofen-pellematic-compact#57]
I can't see my second heating circuit. Only "Hot Water Circuit 1" and "Heating Circuit 1" but I also have another heating circuit in the Pellematic app.

**Comment by dominikamann** [comment]
You must set them up during configuration. You can set the number of heating circuits ("Num of heating circuits (HKx)"). If you want to change it you need to delete and add the Integration again.

**Comment by snuff0815** [comment]
Hi Dominik,

according to your name, can we switch to German?

Unfortunatly I don't get values for heating circuit 2 even if I set the
"num of heating circuits (HKx)" to 2. See screenshot.

[image: image.png]

best regards,
Christoph

Am Mo., 27. Mai 2024 um 16:09 Uhr schrieb Dominik Amann <
***@***.***>:

**Comment by dominikamann** [comment]
Hi Christoph, 

Englisch dient dazu das es die ganze Community versteht. Bitte schick doch mal das JSON-Result der Ökofenschnitstelle durch. Einfach URL (wie bei der Konfiguration) im Browser eingeben und Ergebnis kopieren.
Für mich liest es sich als würde die Ökofenschnittstelle diese Daten nicht durchgeben. Ich weiß, dass zahlreiche User meiner Integration die Funktionalität nutzen daher wundert es mich.

Grüße

**Comment by snuff0815** [comment]
Hi Dominik,

alles klar, wusste nicht, dass die Diskussion dann online ist.

So we switch back to English. Here you can find the JSON result:

Oekofen JSON Interface   V4.02b   http://www.oekofen.at

usage:
http://touch_ip:JSON_port/password/command

====================================================================================
read multiple values:
====================================================================================http://192.168.0.164:4321/********/all?

Example: http://192.168.0.164:4321/********/hk1?


    all[?]     displays values of all available components
               optional parameter [?] adds meta data

    error
        read current errors

    log_today
        download todays csv-logging file
    log_yesterday
        download yesterdays csv-logging file
    log[0..3]
        download csv-logging file

    system[?]
        system global variables

    weather[?]
        current weather data

    forecast[?]
        date|temp|cloud|speed|image|code|unit[|sunrise|sunset] code
see https://openweathermap.org/weather-conditions

    power[?]
        powermeter data

    stirling[?]
        stirling data

    hk[1..6][?]
        heating circuit data

    autocomfort_hk[1..6][?]

    wireless[1..6][?]
        wireless sensor

    thirdparty[1..20][?]
        third party sensor

    pu[1..3][?]
        accu data

    ww[1..3][?]
        domestic hot water data

    sk[1..6][?]
        solar circuit data

    se[1..3][?]
        solar gain data

    circ[1..3][?]
        circulation pump data

    pe[1..4][?]
        pellematic data

====================================================================================
read single value (use '.' as delimitor):
====================================================================================http://192.168.0.164:4321/********/id(1..6).variable

Example: http://192.168.0.164:4321/********/hk1.L_roomtemp_act




====================================================================================
set value (use '.' as delimitor):
====================================================================================http://192.168.0.164:4321/********/id(1..6).variable=value

Example: http://192.168.0.164:4321/********/hk1.mode_auto=0


====================================================================================
alternative useage '_' as delimitor:
====================================================================================http://192.168.0.164:4321/********/id(1..6)_variable=value

Example: http://192.168.0.164:4321/********/hk1_mode_auto=0


    system
        system global variables

    weather
        current weather data

    forecast
        date|temp|cloud|speed|image|code|unit[|sunrise|sunset] code
see https://openweathermap.org/weather-conditions

    power
        powermeter data

    stirling
        stirling data

    hk(1..6)
        heating circuit data

    autocomfort_hk(1..6)

    wireless(1..6)
        wireless sensor

    thirdparty(1..20)
        third party sensor

    pu(1..3)
        accu data

    ww(1..3)
        domestic hot water data

    sk(1..6)
        solar circuit data

    se(1..3)
        solar gain data

    circ(1..3)
        circulation pump data

    pe(1..4)
        pellematic data


only variables without a leading 'L_' can be set.


Am Fr., 31. Mai 2024 um 15:44 Uhr schrieb Dominik Amann <
***@***.***>:

**Comment by dominikamann** [comment]
Kein Problem, bitte den Endpunkt http://[ip]:[port]/[password]/all ausführen. Dort sollten alle Werte zurückkommen. Das Ergebnis oben ist nu die "Start-Seite" der API. Danke.

**Comment by snuff0815** [comment]
wie mache ich das? Also wie "führe ich den Endpunkt aus"? Ich hab wie von
dir gesagt die URL  http://[ip]:[port]/[password]/all in den Browser
eingetragen und dir den Text geschickt.

Am Fr., 7. Juni 2024 um 09:50 Uhr schrieb Dominik Amann <
***@***.***>:

**Comment by dominikamann** [comment]
Wenn ich mir den von dir kopierten Text durchlese steht es anders da. Normal genügt es wirklich http://192.168.0.164:4321/********/all auszuführen mit deiner IP & Passwort. Dann sollten auch die einzel Werte angezeigt werden.
