### ISSUE TITLE
How to find out the pellematic software version

### ISSUE THREAD

**Issue by level420** [dominikamann/oekofen-pellematic-compact#60]
I hope this is not OT, bit I'm struggling finding out which software version my pellematic controller unit has. When looking into the pellematic app I'm getting 

Touch
V3.00b
04112019

Is this sufficient to use the integration?

Thank you in advance

**Comment by dominikamann** [comment]
Hi,
it looks like a very old version. You can see it in the app here:

![image](https://github.com/user-attachments/assets/cf04225f-36c7-4e4a-ae46-adbf10cf664e)

If you are able to activate the JSON-Interface the integration should work 👍

**Comment by level420** [comment]
Sorry for being late with my answer: The version is `Touch V3.00c`.

I've attached the output of
```bash
curl http://my-heaters-ip:4321/myjsonpwd/all > all.json
```
[all.json](https://github.com/user-attachments/files/16441855/all.json)

**Comment by lucaferrucci** [comment]
Hi, I don't know if the version could cause any problems, I still recommend you to do an update of the system, what model do you have?

**Comment by level420** [comment]
@dominikamann @lucaferrucci It's an a 22 years Pellematic 15, where the original Simatic controller was replaced by the current controller with touch display approx. 6 years ago.
But the homeassistant integration is not very important for me, as the Pellematic will be replaced by a heat pump next year.

**Comment by lucaferrucci** [comment]
ahh, ok

**Comment by dominikamann** [comment]
If I look at the json file, it look not that bad. So it should work at least partially. You just have to try it out ;)
