### ISSUE TITLE
Pellet Usage Unknown

### ISSUE THREAD

**Issue by thomas1235678** [dominikamann/oekofen-pellematic-compact#61]
With the Version V4.04 the Pellet Usage is not longer available in Homeassistant.

 With nodered and the json command i got the values:
payload.pe1.L_pellets_today
payload.pe1.L_pellets_yesterday

**Comment by dominikamann** [comment]
Hi @thomas1235678 

can you please post the full json. Are there also other values missing?

That's how we get the value today: 

![image](https://github.com/user-attachments/assets/3b9fb265-7b8e-469e-8960-bd78747196ca)

**Comment by thomas1235678** [comment]
Hi,

{
  "system":{
    "system_info":"system global variables",
    "L_ambient":{"val":182, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Außentemperatur"}, 
    "L_errors":{"val":0, "factor":1, "min":-32768, "max":32767, "text":"Fehler"}, 
    "L_usb_stick":{"val":0, "format":"0:Aus|1:Ein", "text":"Usb Stick erkannt"}, 
    "L_boiler_temp":{"val":502, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Kesseltemperatur"}, 
    "L_existing_boiler":{"val":0, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Bestehender Kessel"}, 
    "mode":{"val":1, "format":"0:Aus|1:Auto|2:Warmwasser", "text":"Betriebsart"}
  },
  "weather":{
    "weather_info":"current weather data",
    "L_temp":{"val":140, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Akt. Temperatur"}, 
    "L_clouds":{"val":3, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"Akt. Bewölkung"}, 
    "L_forecast_temp":{"val":230, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Durchschnittliche Temperatur"}, 
    "L_forecast_clouds":{"val":11, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"Durchschnittliche Bewölkung"}, 
    "L_forecast_today":{"val":1, "format":"0:Heute|1:Morgen", "text":"Wetterprognose start"}, 
    "L_starttime":{"val":800, "factor":1, "min":-32768, "max":32767, "text":"Startzeit"}, 
    "L_endtime":{"val":1800, "factor":1, "min":-32768, "max":32767, "text":"Endzeit"}, 
    "L_source":{"val":"https://www.openweathermap.org", "length":20, "text":"Info"}, 
    "L_location":{"val":"xyz", "length":20, "text":"Ort"}, 
    "cloud_limit":{"val":55, "unit":"%", "factor":1, "min":0, "max":100, "text":"Bewölkungslimit"}, 
    "hysteresys":{"val":-40, "unit":"K", "factor":0.1, "min":-200, "max":0, "text":"Abbruchtmp. Differenz"}, 
    "offtemp":{"val":-100, "unit":"°C", "factor":0.1, "min":-300, "max":200, "text":"Abschalttemperatur"}, 
    "lead":{"val":120, "unit":"min", "factor":1, "min":0, "max":600, "text":"Vorhaltezeit"}, 
    "refresh":{"val":0, "text":"Aktualiseren"}, 
    "oekomode":{"val":1, "format":"0:Aus|1:Ein", "text":"Öko Modus"}
  },
  "forecast":{
    "forecast_info":"date|temp|cloud|speed|image|code|unit[|sunrise|sunset] code see https://openweathermap.org/weather-conditions",
    "L_w_0":{"val":"Mo, 29 Jul 07:05|14|3|4 km/h|01d|800|C|05:35|20:45", "length":20}, 
    "L_w_1":{"val":"Mo, 29 Jul 08:00|14|2|3 km/h|01d|800|C", "length":20}, 
    "L_w_2":{"val":"Mo, 29 Jul 11:00|20|24|4 km/h|02d|801|C", "length":20}, 
    "L_w_3":{"val":"Mo, 29 Jul 14:00|26|19|7 km/h|02d|801|C", "length":20}, 
    "L_w_4":{"val":"Mo, 29 Jul 17:00|26|0|8 km/h|01d|800|C", "length":20}, 
    "L_w_5":{"val":"Mo, 29 Jul 20:00|21|3|7 km/h|01d|800|C", "length":20}, 
    "L_w_6":{"val":"Mo, 29 Jul 23:00|17|0|5 km/h|01n|800|C", "length":20}, 
    "L_w_7":{"val":"Di, 30 Jul 02:00|15|0|7 km/h|01n|800|C", "length":20}, 
    "L_w_8":{"val":"Di, 30 Jul 05:00|13|0|7 km/h|01n|800|C", "length":20}, 
    "L_w_9":{"val":"Di, 30 Jul 08:00|17|0|7 km/h|01d|800|C", "length":20}, 
    "L_w_10":{"val":"Di, 30 Jul 11:00|23|0|11 km/h|01d|800|C", "length":20}, 
    "L_w_11":{"val":"Di, 30 Jul 14:00|27|3|8 km/h|01d|800|C", "length":20}, 
    "L_w_12":{"val":"Di, 30 Jul 17:00|28|51|3 km/h|04d|803|C", "length":20}, 
    "L_w_13":{"val":"Di, 30 Jul 20:00|23|26|2 km/h|03d|802|C", "length":20}, 
    "L_w_14":{"val":"Di, 30 Jul 23:00|18|0|6 km/h|01n|800|C", "length":20}, 
    "L_w_15":{"val":"Mi, 31 Jul 02:00|17|0|5 km/h|01n|800|C", "length":20}, 
    "L_w_16":{"val":"Mi, 31 Jul 05:00|15|2|4 km/h|01n|800|C", "length":20}, 
    "L_w_17":{"val":"Mi, 31 Jul 08:00|19|3|4 km/h|01d|800|C", "length":20}, 
    "L_w_18":{"val":"Mi, 31 Jul 11:00|26|9|6 km/h|01d|800|C", "length":20}, 
    "L_w_19":{"val":"Mi, 31 Jul 14:00|30|5|5 km/h|01d|800|C", "length":20}, 
    "L_w_20":{"val":"Mi, 31 Jul 17:00|31|0|4 km/h|01d|800|C", "length":20}, 
    "L_w_21":{"val":"Mi, 31 Jul 20:00|25|1|3 km/h|01d|800|C", "length":20}, 
    "L_w_22":{"val":"Mi, 31 Jul 23:00|21|25|6 km/h|03n|802|C", "length":20}, 
    "L_w_23":{"val":"Do, 1 Aug 02:00|20|62|24 km/h|10n|500|C", "length":20}, 
    "L_w_24":{"val":"Do, 1 Aug 05:00|18|97|4 km/h|10n|500|C", "length":20}
  },
  "hk1":{
    "hk_info":"heating circuit data",
    "L_roomtemp_act":{"val":225, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Raumtemperatur"}, 
    "roomtemp_act_set":{"val":225, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"VL Ist"}, 
    "L_roomtemp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"RT Soll"}, 
    "L_flowtemp_act":{"val":335, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"VL Ist"}, 
    "L_flowtemp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"VL Soll"}, 
    "L_comfort":{"val":0, "unit":"K", "factor":0.1, "min":-32768, "max":32767, "text":"Komforttemperatur"}, 
    "L_state":{"val":8, "factor":1, "text":"Status"}, 
    "L_statetext":"Betriebsart Aus",
    "L_pump":{"val":0, "format":"0:Aus|1:Ein", "text":"HK Pumpe"}, 
    "remote_override":{"val":0, "unit":"K", "factor":0.1, "min":-32768, "max":32767, "text":"HK Fernbedienung"}, 
    "mode_auto":{"val":0, "format":"0:Aus|1:Auto|2:Heizen|3:Absenken", "text":"Betriebsart"}, 
    "time_prg":{"val":0, "format":"0:Zeit 1|1:Zeit 2", "text":"Zeitauswahl"}, 
    "temp_setback":{"val":180, "unit":"°C", "factor":0.1, "min":100, "max":400, "text":"Raumtemp Absenken"}, 
    "temp_heat":{"val":220, "unit":"°C", "factor":0.1, "min":100, "max":400, "text":"Raumtemp Heizen"}, 
    "temp_vacation":{"val":150, "unit":"°C", "factor":0.1, "min":100, "max":400, "text":"Raumtemp Urlaub"}, 
    "name":{"val":"Badheizkoer.", "length":20, "text":"Anzeigename"}, 
    "oekomode":{"val":0, "format":"0:Aus|1:Komfort|2:Minimum|3:Ökologisch", "text":"Öko Modus"}, 
    "solarheat_mode_auto":{"val":0, "format":"0:Aus|1:Ökologisch|2:Ein", "text":"Betriebsart"}, 
    "solarheat_on_tmp":{"val":800, "unit":"°C", "factor":0.1, "min":300, "max":900, "text":"Einschalttemperatur"}, 
    "solarheat_off_tmp":{"val":700, "unit":"°C", "factor":0.1, "min":300, "max":800, "text":"Abschalttemperatur"}, 
    "solarheat_mode":{"val":0, "format":"0:Vorlauftemp.|1:Raumtemp.", "text":"Heizmodus"}, 
    "solarheat_tmp_set":{"val":300, "unit":"°C", "factor":0.1, "min":200, "max":800, "text":"Vorlauftemperatur"}
  },
  "hk2":{
    "hk_info":"heating circuit data",
    "L_roomtemp_act":{"val":221, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Raumtemperatur"}, 
    "roomtemp_act_set":{"val":221, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"VL Ist"}, 
    "L_roomtemp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"RT Soll"}, 
    "L_flowtemp_act":{"val":248, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"VL Ist"}, 
    "L_flowtemp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"VL Soll"}, 
    "L_comfort":{"val":0, "unit":"K", "factor":0.1, "min":-32768, "max":32767, "text":"Komforttemperatur"}, 
    "L_state":{"val":8, "factor":1, "text":"Status"}, 
    "L_statetext":"Betriebsart Aus",
    "L_pump":{"val":0, "format":"0:Aus|1:Ein", "text":"HK Pumpe"}, 
    "remote_override":{"val":0, "unit":"K", "factor":0.1, "min":-32768, "max":32767, "text":"HK Fernbedienung"}, 
    "mode_auto":{"val":0, "format":"0:Aus|1:Auto|2:Heizen|3:Absenken", "text":"Betriebsart"}, 
    "time_prg":{"val":0, "format":"0:Zeit 1|1:Zeit 2", "text":"Zeitauswahl"}, 
    "temp_setback":{"val":180, "unit":"°C", "factor":0.1, "min":100, "max":400, "text":"Raumtemp Absenken"}, 
    "temp_heat":{"val":220, "unit":"°C", "factor":0.1, "min":100, "max":400, "text":"Raumtemp Heizen"}, 
    "temp_vacation":{"val":150, "unit":"°C", "factor":0.1, "min":100, "max":400, "text":"Raumtemp Urlaub"}, 
    "name":{"val":"FBH", "length":20, "text":"Anzeigename"}, 
    "oekomode":{"val":1, "format":"0:Aus|1:Komfort|2:Minimum|3:Ökologisch", "text":"Öko Modus"}, 
    "solarheat_mode_auto":{"val":0, "format":"0:Aus|1:Ökologisch|2:Ein", "text":"Betriebsart"}, 
    "solarheat_on_tmp":{"val":800, "unit":"°C", "factor":0.1, "min":300, "max":900, "text":"Einschalttemperatur"}, 
    "solarheat_off_tmp":{"val":700, "unit":"°C", "factor":0.1, "min":300, "max":800, "text":"Abschalttemperatur"}, 
    "solarheat_mode":{"val":0, "format":"0:Vorlauftemp.|1:Raumtemp.", "text":"Heizmodus"}, 
    "solarheat_tmp_set":{"val":200, "unit":"°C", "factor":0.1, "min":200, "max":800, "text":"Vorlauftemperatur"}
  },
  "pu1":{
    "pu_info":"accu data",
    "L_tpo_act":{"val":500, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Einschaltfühler"}, 
    "L_tpo_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"TPO Soll"}, 
    "L_tpm_act":{"val":496, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Ausschaltfühler"}, 
    "L_tpm_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"TPM Soll"}, 
    "L_pump_release":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Pumpenfreigabe Temp"}, 
    "L_pump":{"val":0, "unit":"%", "factor":1, "min":0, "max":100, "text":"Drehzahl"}, 
    "L_state":{"val":512, "factor":1, "text":"Status"}, 
    "L_statetext":"Anforderung Aus",
    "mintemp_off":{"val":80, "unit":"°C", "factor":0.1, "min":80, "max":900, "text":"Puffertemp min Aus"}, 
    "mintemp_on":{"val":80, "unit":"°C", "factor":0.1, "min":80, "max":900, "text":"Puffertemp min Ein"}, 
    "ext_mintemp_off":{"val":80, "unit":"°C", "factor":0.1, "min":80, "max":900, "text":"Puffertemp min Aus"}, 
    "ext_mintemp_on":{"val":80, "unit":"°C", "factor":0.1, "min":80, "max":900, "text":"Puffertemp min Ein"}
  },
  "ww1":{
    "ww_info":"domestic hot water data",
    "L_temp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Wassertemp Soll"}, 
    "L_ontemp_act":{"val":514, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Ein Temperatur"}, 
    "L_offtemp_act":{"val":500, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Aus Temperatur"}, 
    "L_pump":{"val":0, "format":"0:Aus|1:Ein", "text":"Pumpe"}, 
    "L_state":{"val":4, "factor":1, "text":"Status"}, 
    "L_statetext":"Betriebsart Aus",
    "time_prg":{"val":0, "format":"0:Zeit 1|1:Zeit 2", "text":"Zeitauswahl"}, 
    "sensor_on":{"val":0, "format":"0:WW|1:TPO|2:TPM|3:SpUnten", "text":"Einschaltfühler"}, 
    "sensor_off":{"val":1, "format":"0:WW|1:TPO|2:TPM|3:SpUnten", "text":"Ausschaltfühler"}, 
    "mode_off":{"val":0, "format":"0:Aus|1:Auto|2:Ein", "text":"Betriebsart"}, 
    "mode_auto":{"val":0, "format":"0:Aus|1:Auto|2:Ein", "text":"Betriebsart"}, 
    "heat_once":{"val":0, "format":"0:Aus|1:Ein", "text":"Einmal Aufbereiten"}, 
    "temp_min_set":{"val":410, "unit":"°C", "factor":0.1, "min":80, "max":800, "text":"Wassertemp Min"}, 
    "temp_max_set":{"val":550, "unit":"°C", "factor":0.1, "min":80, "max":800, "text":"Wassertemp Soll"}, 
    "name":{"val":"Warmwasser ", "length":20, "text":"Anzeigename"}, 
    "smartstart":{"val":90, "unit":"min", "factor":1, "min":0, "max":90, "text":"Intelligenter Start"}, 
    "use_boiler_heat":{"val":0, "format":"0:Aus|1:Ein", "text":"Restwärmenutzung"}, 
    "oekomode":{"val":0, "format":"0:Aus|1:Komfort|2:Minimum|3:Ökologisch", "text":"Öko Modus"}, 
    "solarheat_mode_auto":{"val":0, "format":"0:Aus|1:Ökologisch|2:Ein", "text":"Betriebsart"}, 
    "solarheat_on_tmp":{"val":750, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Einschalttemperatur"}, 
    "solarheat_off_tmp":{"val":600, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Abschalttemperatur"}
  },
  "pe1":{
    "pe_info":"pellematic data",
    "L_temp_act":{"val":502, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Kesseltemperatur"}, 
    "L_temp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"KT Soll"}, 
    "L_ext_temp":{"val":-32768, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Abgastemperatur"}, 
    "L_frt_temp_act":{"val":493, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Flammraumtemp"}, 
    "L_frt_temp_set":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"FRT Soll"}, 
    "L_frt_temp_end":{"val":80, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Flammraumendtemp"}, 
    "L_br":{"val":0, "format":"0:Aus|1:Ein", "text":"Brennerkontakt"}, 
    "L_ak":{"val":0, "format":"0:Aus|1:Ein", "text":"Best Kessel (AK)"}, 
    "L_not":{"val":1, "format":"0:Aus|1:Ein", "text":"Emergency Stop"}, 
    "L_stb":{"val":1, "format":"0:Aus|1:Ein", "text":"Safety Thermostat"}, 
    "L_modulation":{"val":0, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"Modulationsstufe"}, 
    "L_runtimeburner":{"val":0, "unit":"zs", "factor":0.01, "text":"Einschubzeit"}, 
    "L_resttimeburner":{"val":0, "unit":"zs", "factor":0.01, "text":"Pausenzeit"}, 
    "L_currentairflow":{"val":0, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"Lüfter Drehzahl"}, 
    "L_lowpressure":{"val":458, "unit":"EH", "factor":0.1, "min":-32768, "max":32767, "text":"Unterdruck"}, 
    "L_lowpressure_set":{"val":640, "unit":"EH", "factor":0.1, "min":-32768, "max":32767, "text":"Unterdruck Ende"}, 
    "L_fluegas":{"val":0, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"Saugzug Drehzahl"}, 
    "L_uw_speed":{"val":11, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"Drehzahl UW"}, 
    "L_state":{"val":2147483648, "factor":1, "text":"PE Kesselstatus"}, 
    "L_statetext":"Aus",
    "L_type":{"val":6, "format":"0:PE|1:PES|2:PEK|3:PESK|4:SMART V1|5:SMART V2|6:CONDENS|7:SMART XS|8:SMART V3|9:COMPACT|10:AIR|11:CONDENS XL|12:PELLEMATIC HOME", "text":"Kesseltyp"}, 
    "L_starts":{"val":1125, "factor":1, "text":"Brennerstarts"}, 
    "L_runtime":{"val":2655, "unit":"h", "factor":1, "text":"Brennerlaufzeit"}, 
    "L_avg_runtime":{"val":141, "unit":"min", "factor":1, "text":"PE Mittlere Laufzeit"}, 
    "L_uw_release":{"val":500, "unit":"°C", "factor":0.1, "min":-32768, "max":32767, "text":"Freigabetemperatur"}, 
    "L_uw":{"val":11, "unit":"%", "factor":1, "min":-32768, "max":32767, "text":"PE Drehzahl UW"}, 
    "L_storage_fill":{"val":6453, "unit":"kg", "factor":1, "text":"Füllstand Lager"}, 
    "L_storage_min":{"val":1000, "unit":"kg", "factor":1, "min":0, "max":4000, "text":"Warnung bei"}, 
    "L_storage_max":{"val":6500, "unit":"kg", "factor":1, "min":150, "max":30000, "text":"Max. Füllmenge Lager"}, 
    "L_storage_hopper":{"val":31, "unit":"kg", "factor":1, "min":-32768, "max":32767, "text":"Füllstand Zwischenb"}, 
    "L_pellets_today":{"val":0, "unit":"kg", "factor":1, "min":-32768, "max":32767, "text":"Pelletverbrauch heute"}, 
    "L_pellets_yesterday":{"val":3, "unit":"kg", "factor":1, "min":-32768, "max":32767, "text":"Pelletverbrauch gestern"}, 
    "suction_clean_time":{"val":"18:30", "unit":"h", "text":"Reinigung / Befüllung"}, 
    "mode":{"val":1, "format":"0:Aus|1:Auto|2:Ein", "text":"Betriebsart"}
  },
  "error":{
  }
}

**Comment by thomas1235678** [comment]
Also hopper_tank is missing. 
So far i think these three values are missing.

**Comment by dominikamann** [comment]
Hi please test https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v3.3.1
