### ISSUE TITLE
Sensoren "Unbekannt"

### ISSUE THREAD

**Issue by Friesii89** [dominikamann/oekofen-pellematic-compact#70]
Hallo,

nachdem ich nun bereits auf mehreren Wegen versucht habe, meine Pellematic in HomeAssistant einzubinden, ich jedoch immer nur "Unbekannt" als Werte bei den Sensoren erhalte wende ich mich hilfesuchend an euch.
Bei URL habe ich http://192.168.178.83:4321/****/all eingegeben (hierbei sowohl das Passwort, welches mir der Ofen als JSON Passwort anzeigt versucht als auch mein Passwort für die Weboberfläche. JSON Modus ist natürlich auf EIN.

Anbei gleich mal der Auszug des JSON Interface:
Oekofen JSON Interface   V4.00b   http://www.oekofen.at

usage:
http://touch_ip:JSON_port/password/command

====================================================================================
read multiple values:
====================================================================================
http://192.168.178.83:4321/********/all?

Example: http://192.168.178.83:4321/********/hk1?

    all[?]     displays values of all available components
               optional parameter [?] adds meta data

    error
        read current errors

    log[0..3]
        download csv-logging file

    system[?]
        system global variables

    weather[?]
        current weather data

    forecast[?]
        date|temp|cloud|speed|image|code|unit[|sunrise|sunset] code see https://openweathermap.org/weather-conditions

    power[?]
        powermeter data

    stirling[?]
        stirling data

    hk[1..6][?]
        heating circuit data

    thirdparty[1..20][?]
        third party sensor

    pu[1..3][?]
        accu data

    ww[1..3][?]
        domestic hot water data

    sk[1..6][?]
        solar circuit data

    se[1..3][?]
        solar gain data

    circ[1..3][?]
        circulation pump data

    pe[1..4][?]
        pellematic data

====================================================================================
read single value (use '.' as delimitor):
====================================================================================
http://192.168.178.83:4321/********/id(1..6).variable

Example: http://192.168.178.83:4321/********/hk1.L_roomtemp_act

====================================================================================
set value (use '.' as delimitor):
====================================================================================
http://192.168.178.83:4321/********/id(1..6).variable=value

Example: http://192.168.178.83:4321/********/hk1.mode_auto=0

====================================================================================
alternative useage '_' as delimitor:
====================================================================================
http://192.168.178.83:4321/********/id(1..6)_variable=value

Example: http://192.168.178.83:4321/********/hk1_mode_auto=0

    system
        system global variables

    weather
        current weather data

    forecast
        date|temp|cloud|speed|image|code|unit[|sunrise|sunset] code see https://openweathermap.org/weather-conditions

    power
        powermeter data

    stirling
        stirling data

    hk(1..6)
        heating circuit data

    thirdparty(1..20)
        third party sensor

    pu(1..3)
        accu data

    ww(1..3)
        domestic hot water data

    sk(1..6)
        solar circuit data

    se(1..3)
        solar gain data

    circ(1..3)
        circulation pump data

    pe(1..4)
        pellematic data

only variables without a leading 'L_' can be set.

DANKE!

**Comment by dominikamann** [comment]
Hi,
kommen den Werte unter den einzelnen Sektionen wie z.b. HK1 direkt im Browser? Ist eventuell aus versehen der JSON-compatibility-Mode aktiviert im Ökofen-Touch? Ist sichergestellt das HomeAssistant im selben Netzwerk wie die Heizung ist?
Grüße

**Comment by AKL-27** [comment]
Ich hänge mich hier mal mit an. Bisher hole ich die Werte mit der JSON Abfrage in mein IP-Symcon System. Das funktioniert seit Jahren gut. Nun möchte ich voraussichtlich auf Home Assistant umsteigen und versuche, die Anlage in HA abzubilden. Hierfür habe ich deine Software installiert.

Im Browser kann ich sämtliche Werte erfolgreich abfragen. In HA wurden 140 Entitäten erstellt, die leider alle mit „unbekannt“ gekennzeichnet sind.

Hast du einen Tipp?

<Details><summary>Details</summary>
<p>

{
   "system":{
      "L_ambient":"197",
      "L_errors":"0",
      "L_usb_stick":"false"
   },
   "weather":{
      "L_temp":"190",
      "L_clouds":"5",
      "L_forecast_temp":"200",
      "L_forecast_clouds":"93",
      "L_forecast_today":"false",
      "L_starttime":"830",
      "L_endtime":"1740",
      "L_source":"https://www.openweathermap.org",
      "L_location":"xyz",
      "cloud_limit":"55",
      "hysteresys":"-40",
      "offtemp":"-100",
      "lead":"120",
      "refresh":"false",
      "oekomode":"1"
   },
   "forecast":{
      "L_w_0":"So, 31 Aug 21:28|19|5|3 km/h|01n|800|C|06:37|20:07",
      "L_w_1":"So, 31 Aug 23:00|19|8|6 km/h|01n|800|C",
      "L_w_2":"Mo, 1 Sep 02:00|17|26|6 km/h|03n|802|C",
      "L_w_3":"Mo, 1 Sep 05:00|14|47|4 km/h|03n|802|C",
      "L_w_4":"Mo, 1 Sep 08:00|17|74|5 km/h|04d|803|C",
      "L_w_5":"Mo, 1 Sep 11:00|18|88|9 km/h|04d|804|C",
      "L_w_6":"Mo, 1 Sep 14:00|22|93|5 km/h|10d|500|C",
      "L_w_7":"Mo, 1 Sep 17:00|21|98|4 km/h|10d|500|C",
      "L_w_8":"Mo, 1 Sep 20:00|16|99|6 km/h|10d|500|C",
      "L_w_9":"Mo, 1 Sep 23:00|15|100|8 km/h|10n|500|C",
      "L_w_10":"Di, 2 Sep 02:00|14|100|7 km/h|04n|804|C",
      "L_w_11":"Di, 2 Sep 05:00|13|74|5 km/h|04n|803|C",
      "L_w_12":"Di, 2 Sep 08:00|14|87|3 km/h|10d|500|C",
      "L_w_13":"Di, 2 Sep 11:00|14|100|6 km/h|10d|500|C",
      "L_w_14":"Di, 2 Sep 14:00|16|100|4 km/h|10d|500|C",
      "L_w_15":"Di, 2 Sep 17:00|20|84|7 km/h|10d|500|C",
      "L_w_16":"Di, 2 Sep 20:00|15|69|5 km/h|10d|500|C",
      "L_w_17":"Di, 2 Sep 23:00|13|0|6 km/h|01n|800|C",
      "L_w_18":"Mi, 3 Sep 02:00|12|5|6 km/h|01n|800|C",
      "L_w_19":"Mi, 3 Sep 05:00|12|12|7 km/h|02n|801|C",
      "L_w_20":"Mi, 3 Sep 08:00|13|36|6 km/h|03d|802|C",
      "L_w_21":"Mi, 3 Sep 11:00|19|58|11 km/h|04d|803|C",
      "L_w_22":"Mi, 3 Sep 14:00|23|55|11 km/h|10d|500|C",
      "L_w_23":"Mi, 3 Sep 17:00|22|94|6 km/h|04d|804|C",
      "L_w_24":"Mi, 3 Sep 20:00|18|91|1 km/h|04d|804|C"
   },
   "hk1":{
      "L_roomtemp_act":"0",
      "L_roomtemp_set":"80",
      "L_flowtemp_act":"333",
      "L_flowtemp_set":"80",
      "L_state":"8",
      "L_statetext":"Betriebsart Aus",
      "L_pump":"false",
      "mode_auto":"1",
      "time_prg":"0",
      "temp_setback":"165",
      "temp_heat":"220",
      "temp_vacation":"150",
      "name":"",
      "oekomode":"3"
   },
   "pu1":{
      "L_tpo_act":"629",
      "L_tpo_set":"80",
      "L_tpm_act":"622",
      "L_tpm_set":"80",
      "L_pump_release":"80",
      "L_pump":"0",
      "L_state":"512",
      "L_statetext":"Anforderung Aus",
      "mintemp_off":"80",
      "mintemp_on":"80",
      "ext_mintemp_off":"80",
      "ext_mintemp_on":"80"
   },
   "ww1":{
      "L_temp_set":"220",
      "L_ontemp_act":"634",
      "L_offtemp_act":"629",
      "L_pump":"false",
      "L_state":"8200",
      "L_statetext":"Zeit au?erhalb Zeitprogramm|Anforderung Aus",
      "time_prg":"0",
      "sensor_on":"0",
      "sensor_off":"1",
      "mode_auto":"1",
      "mode_dhw":"1",
      "heat_once":"false",
      "temp_min_set":"300",
      "temp_max_set":"500",
      "name":"",
      "smartstart":"0",
      "use_boiler_heat":"0",
      "oekomode":"3"
   },
   "sk1":{
      "L_koll_temp":"201",
      "L_spu":"599",
      "L_pump":"0",
      "L_state":"32",
      "L_statetext":"Differenz Kollektor-Speicher zu niedrig",
      "mode":"1",
      "cooling":"0",
      "spu_max":"750",
      "name":""
   },
   "se1":{
      "L_flow_temp":"307",
      "L_ret_temp":"242",
      "L_flow":"0",
      "L_pwr":"0",
      "L_counter":"30259",
      "L_total":"186419",
      "L_day":"95",
      "L_yesterday":"92"
   },
   "pe1":{
      "L_temp_act":"227",
      "L_temp_set":"80",
      "L_ext_temp":"-32768",
      "L_frt_temp_act":"226",
      "L_frt_temp_set":"80",
      "L_br":"false",
      "L_ak":"false",
      "L_not":"true",
      "L_stb":"true",
      "L_modulation":"0",
      "L_uw_speed":"0",
      "L_state":"99",
      "L_statetext":"Aus",
      "L_type":"1",
      "L_starts":"13340",
      "L_runtime":"8123",
      "L_avg_runtime":"36",
      "L_uw_release":"639",
      "L_uw":"0",
      "L_storage_fill":"0",
      "L_storage_min":"400",
      "L_storage_max":"6000",
      "L_storage_popper":"0",
      "mode":"1"
   },
   "error":{
   }
}

</p>
</details>
