### ISSUE TITLE
Any possibility to set pellematic_heating_circuit_1_flow_temperature_heat and pellematic_heating_circuit_1_temperature_setback?

### ISSUE THREAD

**Issue by cperrier** [dominikamann/oekofen-pellematic-compact#80]
Hello,

The title says it all. Would there be a possibility to *set* the values of these two sensors.

From what I see from the Touch interface of my Pellematic, this is what I can set as "Room Temp Heating" and "Room Temp Set Down".

As of now, in my HA setup, I have automations that change the Pellematic settings with time of the day, presence of ppl in the house, etc. I do this partly with setting the "Op. Mode" from "Heating" to "Set Back" back and forth. Besides that I have more granular settings with the radiators thermostats but that's another story.

Still, after a few weeks of doing this (just to see how the whole house reacts to heating settings and how this influence the pellet consumption which I can now follw since I upgraded to 4.04a firware), I concluded that it would be useful to be able to combine this with changes to both settings of the Heating and Set Back modes....and I guess there may be many use cases for this (sadly the "Auto" mode on the Pellematic is just a joke, IMNSHO....).

So, do you think it could be possible to do this? I can happily help in debugging any development of this issue. Not being neither a Python expert nor an expert in home automation, I very much doubt I could propose a patch, though, sorry for that.

And anyway, huge thanks, again for this amazing work.

**Comment by simonangerbauer** [comment]
@cperrier, controlling "Room Temp Heating" should actually already be possible with your current installation. `number.pellematic_heating_circuit_1_heat_temp` is a number entity you can control.

I added "Room Temp Set Down" (`number.pellematic_heating_circuit_1_set_down_temp`) in PR #82. I guess this should be in the next release.

**Comment by cperrier** [comment]
Oh, indeed, you're absolutely right. So, OK, I can now control one of both.....and soon both thanks to your work.

Much much appreciated! Merci !
