### ISSUE TITLE
Add "Ash amount" sensor ?

### ISSUE THREAD

**Issue by cperrier** [dominikamann/oekofen-pellematic-compact#86]
Having now a nicely working Pellet Storage survey for my Pellemtaci (thaks to firmware updates and recent evolutions of the integration), I, of course, would like more;..:-)

So, I wonder if there could be a way to have a sensor for the ashes amount so that I could setup an alarm in HA in order to think about emptying the ashes storage (something I tend to forget).

I looked at the huge amount of entities provided by the integration and couldn't find this one. On the web interface, it is shown in Plant Overview/Pellematic 1/Filling Level as "PE1 Ash amount" (I guess that if one has more than 1 boiler, this would be "PE1 Ash amount" and "PE2 Ash amount" and so on). Mine is showing 2,4kg as of now which is probably the right value (I can't go and check right now but I may in a few days, if that helps.

I thought that it could help to look at the JSON (I posted one of mine in #78 but I actually can't find anything related to ashes) but it doesn't seem so

**Comment by dominikamann** [comment]
Hi, 
sadly it is not available via the Interface.
At least with the current versions. We discussed this already here https://github.com/dominikamann/oekofen-pellematic-compact/discussions/39. There is an alternative way to achieve it 😉
