### ISSUE TITLE
Is it possible to add the actual warm water temperature?

### ISSUE THREAD

**Issue by laugrean** [dominikamann/oekofen-pellematic-compact#89]
Hey Dominik, 

Really appreciate your project. There is only one thing i miss. Not sure if it is not exported by pellematic at all or not. 
But within the app if you go to your warm water circuit, you can see the values is and should for 
WW Temperature. 
Within your integration i can only find the sensor for "should", in my case this i called:
pellematic_hot_water_circuit_1_temperature_set

I would appreciate to see the current water temperature for my system. 

Thank you in advance!

**Comment by dominikamann** [comment]
Hi 

it should be available see

![image](https://github.com/user-attachments/assets/b3a80320-6680-45e5-b9cc-548d59b146c6)

![image](https://github.com/user-attachments/assets/196ce395-23e0-4f25-bb7f-06edc6f370c0)

**Comment by laugrean** [comment]
Hello!

Sorry i missed this. 
That's what i was looking for. 
Thank you!
