### ISSUE TITLE
Can't see second heating circuit

### ISSUE THREAD

**Issue by freetomfr** [dominikamann/oekofen-pellematic-compact#94]
I have 2 heating circuit. I can see the first one but nothing about the second one.

![image](https://github.com/user-attachments/assets/70ca5066-f57f-460b-8cb6-916c663f9abd)

**Comment by dominikamann** [comment]
Hi, 

it looks like the control feature was only implemented for the first heating circuit. It does not take care about the amount of circuits. So this needs to be extended.

O

**Comment by freetomfr** [comment]
Thanks for your reply. I don't really remember. Is it possible to change this without removing the device and readding it?

**Comment by freetomfr** [comment]
I delete and recreate it chossing 2 heat cirtcuits. It works now! Thanks a lot for your help.
